app:
  name: 'notes'
  version: '1.0.0'

http:
  port: '8081'
  cors: 'http://localhost:3000'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
  # it must be in ENV!
  url: 'postgres://vk:vk@localhost:5432/notes'
